import type { Sector } from './types';

export interface TickerEntry {
  symbol: string;
  name: string;
  sector: Sector;
}

/** Curated US large-cap / mid-cap tech and finance tickers (no API discovery calls). */
export const SCREEN_TICKERS: TickerEntry[] = [
  // Tech (60)
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Tech' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Tech' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', sector: 'Tech' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C', sector: 'Tech' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Tech' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Tech' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Tech' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Tech' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Tech' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Tech' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Tech' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Tech' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Tech' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Tech' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Tech' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Tech' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', sector: 'Tech' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Tech' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Tech' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Tech' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Tech' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Tech' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Tech' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Tech' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Tech' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Tech' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Tech' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', sector: 'Tech' },
  { symbol: 'DDOG', name: 'Datadog Inc.', sector: 'Tech' },
  { symbol: 'NET', name: 'Cloudflare Inc.', sector: 'Tech' },
  { symbol: 'TEAM', name: 'Atlassian Corporation', sector: 'Tech' },
  { symbol: 'SHOP', name: 'Shopify Inc.', sector: 'Tech' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Tech' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Tech' },
  { symbol: 'PLTR', name: 'Palantir Technologies', sector: 'Tech' },
  { symbol: 'RBLX', name: 'Roblox Corporation', sector: 'Tech' },
  { symbol: 'ZM', name: 'Zoom Video Communications', sector: 'Tech' },
  { symbol: 'OKTA', name: 'Okta Inc.', sector: 'Tech' },
  { symbol: 'TWLO', name: 'Twilio Inc.', sector: 'Tech' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Tech' },
  { symbol: 'ADSK', name: 'Autodesk Inc.', sector: 'Tech' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Tech' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'Tech' },
  { symbol: 'HUBS', name: 'HubSpot Inc.', sector: 'Tech' },
  { symbol: 'VEEV', name: 'Veeva Systems', sector: 'Tech' },
  { symbol: 'MDB', name: 'MongoDB Inc.', sector: 'Tech' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Tech' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Tech' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Tech' },
  { symbol: 'IBM', name: 'IBM Corporation', sector: 'Tech' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Tech' },
  { symbol: 'AKAM', name: 'Akamai Technologies', sector: 'Tech' },
  { symbol: 'ZS', name: 'Zscaler Inc.', sector: 'Tech' },
  { symbol: 'DOCU', name: 'DocuSign Inc.', sector: 'Tech' },
  { symbol: 'COIN', name: 'Coinbase Global', sector: 'Tech' },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Tech' },
  { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Tech' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Tech' },
  { symbol: 'MSI', name: 'Motorola Solutions', sector: 'Tech' },
  { symbol: 'CTSH', name: 'Cognizant Technology', sector: 'Tech' },
  // Finance (55)
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Finance' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Finance' },
  { symbol: 'GS', name: 'Goldman Sachs Group', sector: 'Finance' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Finance' },
  { symbol: 'PNC', name: 'PNC Financial Services', sector: 'Finance' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance' },
  { symbol: 'COF', name: 'Capital One Financial', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Finance' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Finance' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Finance' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Finance' },
  { symbol: 'MCO', name: "Moody's Corporation", sector: 'Finance' },
  { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Finance' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Finance' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Finance' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Finance' },
  { symbol: 'TRV', name: 'Travelers Companies', sector: 'Finance' },
  { symbol: 'PGR', name: 'Progressive Corporation', sector: 'Finance' },
  { symbol: 'ALL', name: 'Allstate Corporation', sector: 'Finance' },
  { symbol: 'MET', name: 'MetLife Inc.', sector: 'Finance' },
  { symbol: 'PRU', name: 'Prudential Financial', sector: 'Finance' },
  { symbol: 'AIG', name: 'American International Group', sector: 'Finance' },
  { symbol: 'AFL', name: 'Aflac Incorporated', sector: 'Finance' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Class B', sector: 'Finance' },
  { symbol: 'BX', name: 'Blackstone Inc.', sector: 'Finance' },
  { symbol: 'KKR', name: 'KKR & Co. Inc.', sector: 'Finance' },
  { symbol: 'APO', name: 'Apollo Global Management', sector: 'Finance' },
  { symbol: 'TROW', name: 'T. Rowe Price Group', sector: 'Finance' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation', sector: 'Finance' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Finance' },
  { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Finance' },
  { symbol: 'RF', name: 'Regions Financial', sector: 'Finance' },
  { symbol: 'CFG', name: 'Citizens Financial Group', sector: 'Finance' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Finance' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Finance' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Finance' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', sector: 'Finance' },
  { symbol: 'CMA', name: 'Comerica Incorporated', sector: 'Finance' },
  { symbol: 'ZION', name: 'Zions Bancorporation', sector: 'Finance' },
  { symbol: 'WAL', name: 'Western Alliance Bancorp', sector: 'Finance' },
  { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Finance' },
  { symbol: 'ALLY', name: 'Ally Financial Inc.', sector: 'Finance' },
  { symbol: 'DFS', name: 'Discover Financial Services', sector: 'Finance' },
  { symbol: 'FIS', name: 'Fidelity National Info Services', sector: 'Finance' },
  { symbol: 'FISV', name: 'Fiserv Inc.', sector: 'Finance' },
  { symbol: 'GPN', name: 'Global Payments Inc.', sector: 'Finance' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Finance' },
  { symbol: 'L', name: 'Loews Corporation', sector: 'Finance' },
];
