import type { Sector } from './types';

export interface TickerEntry {
  symbol: string;
  name: string;
  sector: Sector;
}

/** Curated US large-cap tickers across all sectors. Refreshed weekly via Finnhub. */
export const SCREEN_TICKERS: TickerEntry[] = [
  // Tech (60)
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Tech' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Tech' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', sector: 'Tech' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C', sector: 'Tech' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Tech' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Tech' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Tech' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Tech' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Tech' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Tech' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Tech' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Tech' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Tech' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Tech' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Tech' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Tech' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', sector: 'Tech' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Tech' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Tech' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Tech' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Tech' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Tech' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Tech' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Tech' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Tech' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Tech' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Tech' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', sector: 'Tech' },
  { symbol: 'DDOG', name: 'Datadog Inc.', sector: 'Tech' },
  { symbol: 'NET', name: 'Cloudflare Inc.', sector: 'Tech' },
  { symbol: 'TEAM', name: 'Atlassian Corporation', sector: 'Tech' },
  { symbol: 'SHOP', name: 'Shopify Inc.', sector: 'Tech' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Tech' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Tech' },
  { symbol: 'PLTR', name: 'Palantir Technologies', sector: 'Tech' },
  { symbol: 'RBLX', name: 'Roblox Corporation', sector: 'Tech' },
  { symbol: 'ZM', name: 'Zoom Video Communications', sector: 'Tech' },
  { symbol: 'OKTA', name: 'Okta Inc.', sector: 'Tech' },
  { symbol: 'TWLO', name: 'Twilio Inc.', sector: 'Tech' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Tech' },
  { symbol: 'ADSK', name: 'Autodesk Inc.', sector: 'Tech' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Tech' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'Tech' },
  { symbol: 'HUBS', name: 'HubSpot Inc.', sector: 'Tech' },
  { symbol: 'VEEV', name: 'Veeva Systems', sector: 'Tech' },
  { symbol: 'MDB', name: 'MongoDB Inc.', sector: 'Tech' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Tech' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Tech' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Tech' },
  { symbol: 'IBM', name: 'IBM Corporation', sector: 'Tech' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Tech' },
  { symbol: 'AKAM', name: 'Akamai Technologies', sector: 'Tech' },
  { symbol: 'ZS', name: 'Zscaler Inc.', sector: 'Tech' },
  { symbol: 'DOCU', name: 'DocuSign Inc.', sector: 'Tech' },
  { symbol: 'COIN', name: 'Coinbase Global', sector: 'Tech' },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Tech' },
  { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Tech' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Tech' },
  { symbol: 'MSI', name: 'Motorola Solutions', sector: 'Tech' },
  { symbol: 'CTSH', name: 'Cognizant Technology', sector: 'Tech' },
  // Finance (55)
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Finance' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Finance' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Finance' },
  { symbol: 'GS', name: 'Goldman Sachs Group', sector: 'Finance' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Finance' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Finance' },
  { symbol: 'PNC', name: 'PNC Financial Services', sector: 'Finance' },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance' },
  { symbol: 'COF', name: 'Capital One Financial', sector: 'Finance' },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Finance' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Finance' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Finance' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Finance' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Finance' },
  { symbol: 'MCO', name: "Moody's Corporation", sector: 'Finance' },
  { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Finance' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Finance' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Finance' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Finance' },
  { symbol: 'TRV', name: 'Travelers Companies', sector: 'Finance' },
  { symbol: 'PGR', name: 'Progressive Corporation', sector: 'Finance' },
  { symbol: 'ALL', name: 'Allstate Corporation', sector: 'Finance' },
  { symbol: 'MET', name: 'MetLife Inc.', sector: 'Finance' },
  { symbol: 'PRU', name: 'Prudential Financial', sector: 'Finance' },
  { symbol: 'AIG', name: 'American International Group', sector: 'Finance' },
  { symbol: 'AFL', name: 'Aflac Incorporated', sector: 'Finance' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Class B', sector: 'Finance' },
  { symbol: 'BX', name: 'Blackstone Inc.', sector: 'Finance' },
  { symbol: 'KKR', name: 'KKR & Co. Inc.', sector: 'Finance' },
  { symbol: 'APO', name: 'Apollo Global Management', sector: 'Finance' },
  { symbol: 'TROW', name: 'T. Rowe Price Group', sector: 'Finance' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation', sector: 'Finance' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Finance' },
  { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Finance' },
  { symbol: 'RF', name: 'Regions Financial', sector: 'Finance' },
  { symbol: 'CFG', name: 'Citizens Financial Group', sector: 'Finance' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Finance' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Finance' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Finance' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', sector: 'Finance' },
  { symbol: 'CMA', name: 'Comerica Incorporated', sector: 'Finance' },
  { symbol: 'ZION', name: 'Zions Bancorporation', sector: 'Finance' },
  { symbol: 'WAL', name: 'Western Alliance Bancorp', sector: 'Finance' },
  { symbol: 'SYF', name: 'Synchrony Financial', sector: 'Finance' },
  { symbol: 'ALLY', name: 'Ally Financial Inc.', sector: 'Finance' },
  { symbol: 'DFS', name: 'Discover Financial Services', sector: 'Finance' },
  { symbol: 'FIS', name: 'Fidelity National Info Services', sector: 'Finance' },
  { symbol: 'FISV', name: 'Fiserv Inc.', sector: 'Finance' },
  { symbol: 'GPN', name: 'Global Payments Inc.', sector: 'Finance' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', sector: 'Finance' },
  { symbol: 'L', name: 'Loews Corporation', sector: 'Finance' },
  // Healthcare (48)
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck & Co.', sector: 'Healthcare' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Healthcare' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Healthcare' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Healthcare' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', sector: 'Healthcare' },
  { symbol: 'DXCM', name: 'DexCom Inc.', sector: 'Healthcare' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'CI', name: 'The Cigna Group', sector: 'Healthcare' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana Inc.', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Healthcare' },
  { symbol: 'MCK', name: 'McKesson Corporation', sector: 'Healthcare' },
  { symbol: 'CAH', name: 'Cardinal Health', sector: 'Healthcare' },
  { symbol: 'COR', name: 'Cencora Inc.', sector: 'Healthcare' },
  { symbol: 'BDX', name: 'Becton Dickinson', sector: 'Healthcare' },
  { symbol: 'IQV', name: 'IQVIA Holdings', sector: 'Healthcare' },
  { symbol: 'A', name: 'Agilent Technologies', sector: 'Healthcare' },
  { symbol: 'RMD', name: 'ResMed Inc.', sector: 'Healthcare' },
  { symbol: 'MTD', name: 'Mettler-Toledo', sector: 'Healthcare' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Technology', sector: 'Healthcare' },
  { symbol: 'HOLX', name: 'Hologic Inc.', sector: 'Healthcare' },
  { symbol: 'PODD', name: 'Insulet Corporation', sector: 'Healthcare' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare' },
  { symbol: 'CNC', name: 'Centene Corporation', sector: 'Healthcare' },
  { symbol: 'MOH', name: 'Molina Healthcare', sector: 'Healthcare' },
  { symbol: 'UHS', name: 'Universal Health Services', sector: 'Healthcare' },
  { symbol: 'DVA', name: 'DaVita Inc.', sector: 'Healthcare' },
  { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'Healthcare' },
  { symbol: 'ILMN', name: 'Illumina Inc.', sector: 'Healthcare' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'Healthcare' },
  // Energy (48)
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger Limited', sector: 'Energy' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy' },
  { symbol: 'CTRA', name: 'Coterra Energy', sector: 'Energy' },
  { symbol: 'OKE', name: 'ONEOK Inc.', sector: 'Energy' },
  { symbol: 'TRGP', name: 'Targa Resources', sector: 'Energy' },
  { symbol: 'EPD', name: 'Enterprise Products Partners', sector: 'Energy' },
  { symbol: 'ET', name: 'Energy Transfer LP', sector: 'Energy' },
  { symbol: 'LNG', name: 'Cheniere Energy', sector: 'Energy' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy' },
  { symbol: 'VST', name: 'Vistra Corp.', sector: 'Energy' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Energy' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Energy' },
  { symbol: 'AEP', name: 'American Electric Power', sector: 'Energy' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Energy' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Energy' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Energy' },
  { symbol: 'EXC', name: 'Exelon Corporation', sector: 'Energy' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Energy' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Energy' },
  { symbol: 'FE', name: 'FirstEnergy Corp.', sector: 'Energy' },
  { symbol: 'ES', name: 'Eversource Energy', sector: 'Energy' },
  { symbol: 'PPL', name: 'PPL Corporation', sector: 'Energy' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Energy' },
  { symbol: 'WEC', name: 'WEC Energy Group', sector: 'Energy' },
  { symbol: 'CMS', name: 'CMS Energy', sector: 'Energy' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Energy' },
  { symbol: 'PCG', name: 'PG&E Corporation', sector: 'Energy' },
  { symbol: 'ATO', name: 'Atmos Energy', sector: 'Energy' },
  { symbol: 'CNP', name: 'CenterPoint Energy', sector: 'Energy' },
  { symbol: 'NI', name: 'NiSource Inc.', sector: 'Energy' },
  { symbol: 'OGE', name: 'OGE Energy Corp.', sector: 'Energy' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group', sector: 'Energy' },
  { symbol: 'AWK', name: 'American Water Works', sector: 'Energy' },
  { symbol: 'FTI', name: 'TechnipFMC plc', sector: 'Energy' },
  // Consumer (48)
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer' },
  { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer' },
  { symbol: 'HD', name: 'The Home Depot', sector: 'Consumer' },
  { symbol: 'LOW', name: "Lowe's Companies", sector: 'Consumer' },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer' },
  { symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer' },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer' },
  { symbol: 'PM', name: 'Philip Morris International', sector: 'Consumer' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer' },
  { symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer' },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer' },
  { symbol: 'K', name: 'Kellanova', sector: 'Consumer' },
  { symbol: 'HSY', name: 'The Hershey Company', sector: 'Consumer' },
  { symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer' },
  { symbol: 'TAP', name: 'Molson Coors Beverage', sector: 'Consumer' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer' },
  { symbol: 'EL', name: 'The Estée Lauder Companies', sector: 'Consumer' },
  { symbol: 'CLX', name: 'The Clorox Company', sector: 'Consumer' },
  { symbol: 'CHD', name: 'Church & Dwight', sector: 'Consumer' },
  { symbol: 'NKE', name: 'NIKE Inc.', sector: 'Consumer' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer' },
  { symbol: 'MCD', name: "McDonald's Corporation", sector: 'Consumer' },
  { symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer' },
  { symbol: 'DPZ', name: "Domino's Pizza", sector: 'Consumer' },
  { symbol: 'DRI', name: 'Darden Restaurants', sector: 'Consumer' },
  { symbol: 'MAR', name: 'Marriott International', sector: 'Consumer' },
  { symbol: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer' },
  { symbol: 'RCL', name: 'Royal Caribbean Group', sector: 'Consumer' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line', sector: 'Consumer' },
  { symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer' },
  { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer' },
  { symbol: 'MGM', name: 'MGM Resorts International', sector: 'Consumer' },
  { symbol: 'TJX', name: 'The TJX Companies', sector: 'Consumer' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Consumer' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", sector: 'Consumer' },
  { symbol: 'AZO', name: 'AutoZone Inc.', sector: 'Consumer' },
  { symbol: 'BBY', name: 'Best Buy Co.', sector: 'Consumer' },
  { symbol: 'TSCO', name: 'Tractor Supply Company', sector: 'Consumer' },
  { symbol: 'PHM', name: 'PulteGroup Inc.', sector: 'Consumer' },
  { symbol: 'DHI', name: 'D.R. Horton', sector: 'Consumer' },
  { symbol: 'LEN', name: 'Lennar Corporation', sector: 'Consumer' },
  { symbol: 'GM', name: 'General Motors', sector: 'Consumer' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer' },
];
